---
# manual_metadata
# Please find the BIDS specification here: https://bids-specification--1128.org.readthedocs.build/en/1128/modality-specific-files/eye-tracking.html
# Please go through the specification and fille the fields below according to the data types given in the specification.

# REQUIRED, fill according to BIDS specification (!the converter will not run successfully if you leave this empty!):
SampleCoordinateUnits: ''
SampleCoordinateSystem: ''
EnvironmentCoordinates: ''
ScreenDistance:
ScreenRefreshRate:
ScreenSize:

# Recommended (leave empty if not available but put information you want to share with your dataset here!):
SoftwareVersion: ''
ScreenAOIDefinition:
EyeCameraSettings:
EyeTrackerDistance:
FeatureDetectionSettings:
GazeMappingSettings:
RawDataFilters:
InstitutionName: ''
InstitutionAddress: ''
