---
# manual_metadata

# Required, fill according to BIDS specification:
SampleCoordinateUnits: ''
SampleCoordinateSystem: ''
EnvironmentCoordinates: ''
ScreenDistance:
ScreenRefreshRate:
ScreenSize:
InstitutionName: ''
InstitutionAddress: ''

# Recommended, leave empty if not available:
SoftwareVersion: ''
ScreenAOIDefinition:
EyeCameraSettings:
EyeTrackerDistance:
FeatureDetectionSettings:
GazeMappingSettings:
RawDataFilters:
